### ISSUE TITLE
Favicons leaking host url to DDG server

### ISSUE THREAD

**Issue by pythoneer** [duckduckgo/iOS#665] opened 2020-07-02 09:53 UTC
As a sibling of the ["same" issue](https://github.com/duckduckgo/Android/issues/527) on [the Android](https://github.com/duckduckgo/Android/issues/876) side, the iOS App has the same Problem.
[this](https://github.com/duckduckgo/iOS/blob/1ae03d7221180bd6791cf6f7f06922a96335cf75/Core/AppUrls.swift#L98)
```swift
    static let externalContentBase = "https://external-content.duckduckgo.com"
    static let faviconService = "\(externalContentBase)/ip3/%@.ico"

    public func faviconUrl(forDomain domain: String) -> URL? {
        let urlString = String(format: Url.faviconService, domain)
        return URL(string: urlString)
    }
```

Is sending the host domain url to the DDG server.

Locks like it is used for [every opened tab](https://github.com/duckduckgo/iOS/blob/c5fe52b08432d55f9d38fb799578037c421a04f4/DuckDuckGo/TabViewCell.swift#L284) and everything in [the bookmarks](https://github.com/duckduckgo/iOS/blob/d9272abaafd5472b8a0b6fcb35be25b854b5cf74/BookmarksTodayExtension/BookmarkCell.swift#L37)

```swift
    private func configureFavicon(forDomain domain: String?) {
        let placeholder = #imageLiteral(resourceName: "GlobeSmall")
        favicon.image = placeholder

        if let domain = domain {
            let faviconUrl = AppUrls().faviconUrl(forDomain: domain)
            favicon.kf.setImage(with: faviconUrl,
                                  placeholder: placeholder,
                                  options: [.downloader(NotFoundCachingDownloader())],
                                  progressBlock: nil,
                                  completionHandler: nil)
        }
    }
```

```swift
    private func configureFavicon(forDomain domain: String?) {
        favicon.image = BookmarkCell.placeholderFavicon
        if let domain = domain {
            let faviconUrl = AppUrls().faviconUrl(forDomain: domain)
            favicon.kf.setImage(with: faviconUrl, placeholder: BookmarkCell.placeholderFavicon)
        }
    }
```

**Comment by catehstn** [comment] 2020-07-02 14:35
Duplicate of #666, addressed in #667 (currently in review).

**Closed as completed by catehstn** 2020-07-02 14:35 UTC
